Allow specifying API path instead of hostname
aranajuan/joplin-plugin-timetagger pull request #2
Opened 2022-09-16 09:59 UTC by almarklein

Hi!

TimeTagger dev here :)  I just learned about this plugin. Nice to see timetagger finding its way to other tools!

I got a question from a user though, which lead me to this PR.

The way that the API endpoint is calculated assumes the default self-hosting API path. E.g. for timetagger.app, the API path is `https://timetagger.app/api/`, but this cannot be used right now. This PR allows specifying the full API path to work around this limitation.

2022-09-16 10:01 UTC, almarklein commented
For the record. Self-hosters can also chose to host at another path than the `/timetagger/` prefix, so it would be problematic in these situations as well.

2022-09-17 22:59 UTC, aranajuan commented
Thank you man! I had this fix in my backlog but I didn't find the time.
I think I will be pushing to npm today or tomorrow.
Btw, thank u for timetagger :)

2022-09-17 23:24 UTC, aranajuan requested changes

2022-09-17 23:24 UTC, aranajuan commented on src/timetagger.ts
> +				this.serverHost=host+"v2";
I think that if someone write the full URL is weird to modify it.
ie; if someone write https://timetagger.app/api/v2 this logic will break. right?

I think that if URL contains "/api" is because the user knows what he is doing.
My proposal is:
1. if host contains "/api" we use it as it is
2. if https://timetagger.app we add the default "/api/v2"
3. otherwise we add "/timetagger/api/v2"

2022-09-17 23:25 UTC, aranajuan commented on src/timetagger.ts
> +				this.serverHost=host+"v2";
what do you think?

2022-09-18 08:49 UTC, almarklein commented on src/timetagger.ts
> +				this.serverHost=host+"v2";
I thought of that too. One argument for leaving out the "v2" part is that if there ever comes a "v3" (nothing planned!), users won't have to update their config.

On the other hand, I agree that it might feel a bit odd that one has to provide *almost* the full url. Plus you can always replace "v2" with "v3" if its ever needed.

I like your suggestion - let's go with that :)

2022-09-18 09:06 UTC, almarklein commented on src/timetagger.ts
> +			}
```suggestion
			if(host.endsWith("/")){
				host = host.slice(0,-1);
			}
			if(host.indexOf("/api")>0){
				// full URL, assume that user knows what to do
				this.serverHost=host;
			} else if(host="https://timetagger.app"){
				// Using timetagger.app service
				this.serverHost=host+"/api/v2";
			}else{
				// assume default self-hosting API endpoint
				this.serverHost=host+"/timetagger/api/v2";
			}
```

2022-09-18 14:06 UTC, aranajuan approved these changes

2022-09-18 14:07 UTC, merged

2022-09-19 22:33 UTC, aranajuan commented
@almarklein done! 
https://www.npmjs.com/package/joplin-plugin-timetagger/v/1.1.0
It takes some time to be available for joplin's users in plugin section. Let me know if you have other ideas :D

2022-09-19 23:11 UTC, almarklein commented
Thanks for the heads-up!